<a href="https://colab.research.google.com/github/YuDeokRin/ICT_innovation_square/blob/main/04.Deep%20Learning/3_%EC%9D%B8%EA%B3%B5_%EC%8B%A0%EA%B2%BD%EB%A7%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#AND연산의 x1,x2입력을 저장하는 배열
X=  np.array([
              [0., 0.],
              [0., 1.],
              [1., 0.],
              [1., 1.]
         ],dtype="float32")

In [ ]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [ ]:
#AND연산의 y출력을 저장하는 배열
y = np.array( [
              [0.],
              [0.],
              [0.],
              [1.]
     ], dtype="float32")

In [ ]:
y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [ ]:
#X에 곱해지는 값 선언
w = np.array([[1],[2]], dtype="float32")
#X에 더해지는 값 선언
b = np.array([3],dtype="float32")

In [ ]:
w

array([[1.],
       [2.]], dtype=float32)

In [ ]:
b

array([3.], dtype=float32)

In [ ]:
#X에 w를 곱함
np.dot(X,w)

array([[0.],
       [2.],
       [1.],
       [3.]], dtype=float32)

In [ ]:
#X에 w를 곱하고 b를 더함
np.dot(X,w)+b

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [ ]:
#h를 0~1 사이 범위로 변경하는 활성함수 선언
def sigmoid(h):
    return 1 / (1 +np.exp(-h))

In [ ]:
#X*W+b를 실행해서 예측값을 hypothesis에 대입
hypothesis = np.dot(X,w)+b
hypothesis

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [ ]:
#X*W+b를 실행해서 예측값을 hypothesis에 대입하고 활성함수를 이용해서 
#값의 범위를 0~1 사이로 변경
hypothesis = sigmoid(np.dot(X,w)+b)
hypothesis

array([[0.95257413],
       [0.9933072 ],
       [0.98201376],
       [0.9975274 ]], dtype=float32)

In [ ]:
#예측값-실제값
(hypothesis-y)

array([[ 0.95257413],
       [ 0.9933072 ],
       [ 0.98201376],
       [-0.00247258]], dtype=float32)

In [ ]:
#X의 줄칸을 반대로 전환
X.T

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]], dtype=float32)

In [ ]:
#X의 줄칸을 반대로 전환하고 0번째 줄을 리턴
#X의 줄칸을 반대로 전환했기 때문에 실제로는 0번째 칸이 리턴됨
X.T[0]

array([0., 0., 1., 1.], dtype=float32)

In [ ]:
#이차원 배열인 (hypothesis-y) 와 변환 하기 위해서
#X.T[0] 를 2차원 배열로 변환
X_col_2d1 = X.T[0].reshape(1, -1)
X_col_2d1

array([[0., 0., 1., 1.]], dtype=float32)

In [ ]:
#w1의 수정값
w1_gred = 1/4*np.sum(np.dot(X_col_2d1,(hypothesis-y)))
print("w_gred:",w1_gred)

w_gred: 0.24488529562950134


In [ ]:
#X의 줄칸을 반대로 전환하고 1번째 줄을 리턴
#X의 줄칸을 반대로 전환했기 때문에 실제로는 1번째 칸이 리턴됨
X.T[1]

array([0., 1., 0., 1.], dtype=float32)

In [ ]:
#이차원 배열인 (hypothesis-y) 와 변환 하기 위해서
#X.T[1] 를 2차원 배열로 변환
X_col_2d2 = X.T[1].reshape(1, -1)
X_col_2d2

array([[0., 1., 0., 1.]], dtype=float32)

In [ ]:
#w2의 수정값
w2_gred = 1/4*np.sum(np.dot((hypothesis-y),X_col_2d2))
print("w_gred:",w2_gred)

w_gred: 1.4627113342285156


In [ ]:
#b의 수정값
b_gred = 1/4 * np.sum(hypothesis-y)
print("b_gred:",b_gred)

b_gred: 0.731355607509613


In [ ]:
#learninng rate
learning_rate=0.1

#1000 번 반복해서 오차 제곱의 합이 0으로 수렴되는 w와 b를 찾음
for i in range(1000):
    for j in range(2):
        #예측값을 hypothesis에 대입
        hypothesis = sigmoid(np.dot(X,w)+b)
        print("hypothesis:",hypothesis)
        #오차를 계산
        cost = -1/4*(y * np.log(hypothesis) + (1 - y) * np.log(1 - hypothesis))
        print("cost:",cost)
        #X의 줄 칸을 변경하여 j번째 칸을 리턴 2차원 배열로 생성
        X_col_2d = X.T[j].reshape(1, -1)
        #w의 기울기를 계산
        w_gred = 1/4*np.sum(np.dot(X_col_2d,(hypothesis-y)))
        print("w_{}gred:{}".format(i,w_gred))
        #w를 업데이트
        w[j]=w[j]-learning_rate*w_gred
        print("w{}:{}".format(j,w))
        #b의 기울기를 계산
        b_gred = 1/4 * np.sum(hypothesis-y)
        print("b{}_gred:{}".format(i,b_gred))
        #b를 업데이트
        b=b-learning_rate*b_gred
        print("b:{}".format(b))
        

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [0.03365902]
 [0.05762597]]
w_807gred:-0.018711164593696594
w1:[[3.2419755]
 [3.2890003]]
b807_gred:0.014180764555931091
b:[-5.1805]
hypothesis: [[0.00559373]
 [0.13107356]
 [0.12581006]
 [0.79420745]]
cost: [[0.00140236]
 [0.03512421]
 [0.03361439]
 [0.05760264]]
w_808gred:-0.01999562233686447
w0:[[3.2439752]
 [3.2890003]]
b808_gred:0.014171198010444641
b:[-5.181917]
hypothesis: [[0.00558585]
 [0.13091224]
 [0.12587412]
 [0.7943026 ]]
cost: [[0.00140038]
 [0.0350778 ]
 [0.03363272]
 [0.0575727 ]]
w_808gred:-0.018696293234825134
w1:[[3.2439752]
 [3.29087  ]]
b808_gred:0.014168694615364075
b:[-5.183334]
hypothesis: [[0.00557799]
 [0.13096379]
 [0.12571833]
 [0.7943767 ]]
cost: [[0.0013984 ]
 [0.03509263]
 [0.03358818]
 [0.05754938]]
w_809gred:-0.01997625082731247
w0:[[3.2459729]
 [3.29087  ]]
b809_gred:0.0141591876745224
b:[-5.1847496]
hypothesis: [[0.00557014]
 [0.13080274]
 [0.12578231]
 [0.7944716 ]]
cost: [[0.00139642]
 [0.0350463 ]
 [0.03360647]

In [ ]:
#Gradient Decent로 계산한 w
w

array([[3.5944264],
       [3.6230006]], dtype=float32)

In [ ]:
#Gradient Decent로 계산한 b
b

array([-5.684683], dtype=float32)

In [ ]:
#X에 w를 곱하고 b를 추가
np.dot(X,w)+b

array([[-5.684683 ],
       [-2.0616822],
       [-2.0902565],
       [ 1.5327444]], dtype=float32)

In [ ]:
##X에 w를 곱하고 b를 추가한후 활성함수를 이용해서 데이터의 범위를 0~1로 설정
predict =sigmoid(np.dot(X,w)+b)
predict

array([[0.00338611],
       [0.11287727],
       [0.11004746],
       [0.8224075 ]], dtype=float32)

In [ ]:
#True를 정수로 변환 -> 1
int(True)

1

In [ ]:
#False를 정수로 변환 ->0
int(False)

0

In [ ]:
#np.where(조건, 조건만족시 리턴할 값, 조건 거짓일때 리턴할 값)
#np.where(predict >0.5, 1, 0) : predict 에 저장된 값이 0.5 초과면 1리턴 아니면 0 리턴

predict01 = np.where(predict>=0.5, 1, 0)
print("====================================")
print("predict01")
print(predict01)

predict01
[[0]
 [0]
 [0]
 [1]]


In [ ]:
#predict01 == y 가 같으면 true 다르면 false 리턴
predict02 = (predict01 == y)
predict02

array([[ True],
       [ True],
       [ True],
       [ True]])

In [ ]:
#True는 1로 False는 0으로 변환 해서 합을 계산
np.sum(predict02)

4

In [ ]:
#정확도를 계산
acc=np.sum(predict02)/4
acc

1.0

In [ ]:
#0,1 의 and 연산 실행
arr=np.array([[0,1]], dtype="float32")
#sigmoid(arr*w+b) 를 계산
predict=sigmoid(np.dot(arr,w)+b)
predict

array([[0.11287727]], dtype=float32)

In [ ]:
#np.where(조건, 조건만족시 리턴할 값, 조건 거짓일때 리턴할 값)
#np.where(predict >0.5, 1, 0) : predict 에 저장된 값이 0.5 초과면 1리턴 아니면 0 리턴

predict01 = np.where(predict>=0.5, 1, 0)
print("====================================")
print("predict01")
print(predict01)

predict01
[[0]]


In [ ]:
#1,1 의 and 연산 실행
arr=np.array([[1,1]], dtype="float32")
#sigmoid(arr*w+b) 를 계산
predict=sigmoid(np.dot(arr,w)+b)
predict

array([[0.8224075]], dtype=float32)

In [ ]:
#np.where(조건, 조건만족시 리턴할 값, 조건 거짓일때 리턴할 값)
#np.where(predict >0.5, 1, 0) : predict 에 저장된 값이 0.5 초과면 1리턴 아니면 0 리턴

predict01 = np.where(predict>=0.5, 1, 0)
print("====================================")
print("predict01")
print(predict01)

predict01
[[1]]
